name: JavaFX Build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installer Java 25
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '25'

      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Build JavaFX
        run: mvn clean package

      - name: Générer l'exécutable Linux
        run: |
          mkdir -p dist
          export JAVAFX_LIB="/usr/share/openjfx/lib"
          MAIN_JAR=$(ls target/*.jar | xargs -n 1 basename)
          jpackage \
            --input target \
            --name FloteoApp \
            --main-jar $MAIN_JAR \
            --main-class com.floteo.ui.InterfaceApp \
            --type app-image \
            --module-path $JAVAFX_LIB \
            --add-modules javafx.controls,javafx.fxml \
            --dest dist

      - name: Publier les artefacts
        uses: actions/upload-artifact@v4
        with:
          name: javafx-app
          path: |
            target/*.jar
            dist/*
